### ISSUE TITLE
undefined button

### ISSUE THREAD

**Issue by matheusamendola** [cconard96/glpi-stab-plugin#2]
Good afternoon,
Sometimes when the person goes to add a reply it appears 'undefined' and the status is not changed if you click like this. 
I think it only happens with the translation in Portuguese - Brazil. When I switched to English it didn't happen 

![image](https://user-images.githubusercontent.com/37221484/173450552-97f70d25-647a-40cc-8a1a-fed00c0af9a1.png)

If I change to another status and click on closed again it appears normally

![image](https://user-images.githubusercontent.com/37221484/173450603-0308be98-a119-41a1-8b01-e45705bcfddb.png)

**Comment by cconard96** [comment]
I am not seeing this issue with the Portuguese - Brazil language.
When you initially open the form, there should just be the text "Add" with no icon.
Selecting other statuses seem to update the icon as expected.

Are there any warnings or errors logged to the browser's console (F12 Key > Console tab) when this issue occurs?

**Comment by matheusamendola** [comment]
only this appears on console
![image](https://user-images.githubusercontent.com/37221484/173582539-66778598-1477-46ab-8784-3b7b6b8ec7e2.png)

the undefined message appears only when I click on the closed option

**Comment by cconard96** [comment]
I've still not been able to recreate the issue but the changes made in #3 may fix the issue.
Can you test these changes?

You can manually make the changes, or use the raw file from the pull request:
https://raw.githubusercontent.com/cconard96/glpi-stab-plugin/7c6e460f0724ee472464185db837df5214271056/js/stab.js
