### ISSUE TITLE
 Undefined array key "REQUEST_URI"

### ISSUE THREAD

**Issue by DooBio** [cconard96/glpi-stab-plugin#4]
Hello

it's probably nothing but I'm used to giving you error messages ;)

when I am in console I have this alert for a short time:

`PHP Warning:  Undefined array key "REQUEST_URI" in /var/www/glpi/marketplace/stab/setup.php on line 34`

It's weird because the plugin has been active for several months

---
GLPI 10.0.2
Apache/2.4.53
PHP version (8.1.7)
stab plugin  Version: 1.0.1

**Comment by DooBio** [comment]
[2022-08-18 16:29:03] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "REQUEST_URI" in /var/www/glpi/marketplace/stab/setup.php at line 34
  Backtrace :
  src/Plugin.php:288                                 plugin_init_stab()
  src/Plugin.php:238                                 Plugin::load()
  src/Console/Application.php:118                    Plugin->init()
  bin/console:121                                    Glpi\Console\Application->__construct()

**Comment by cconard96** [comment]
Fixed via a0f80fb6fa4e309587e6d5567261de220812c348 and released it as v1.0.2.
https://github.com/cconard96/glpi-stab-plugin/releases/tag/v1.0.2
