### ISSUE TITLE
Missing menu in a task

### ISSUE THREAD

**Issue by Rom1-B** [cconard96/glpi-stab-plugin#7]
Hello,

We have the menu in a follow-up, but in a task, it is empty.

Follow-up:

![image](https://user-images.githubusercontent.com/8530352/191899937-0afa7db1-4c22-4bb5-b00d-69ec47e55742.png)

Task:

![image](https://user-images.githubusercontent.com/8530352/191900140-75716d36-3593-4988-a92a-ab593ba5c59b.png)

**Comment by cconard96** [comment]
Hello.

This should have been fixed in the v1.1.1 release done yesterday.

**Comment by Rom1-B** [comment]
Hello Curtis,

Sorry, I forgot to mention that I tested in 1.1.1

**Comment by cconard96** [comment]
This should be fixed by #8. I'll wait for confirmation before merging and making another release.

**Comment by Rom1-B** [comment]
Yes, it works for me.

Thanks
